#총매출액 계산
SELECT F.PRODUCT_ID, F.PRODUCT_NAME, (F.PRICE * S.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS F
JOIN (
    #ID가 같은 상품 AMOUNT 합산
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM (
        #생산일자(PRODUCE_DATE) 2022년 5월 식품들만 필터링
        SELECT PRODUCT_ID, AMOUNT
        FROM FOOD_ORDER
        WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    ) AS FILTER
    GROUP BY PRODUCT_ID
) AS S
ON F.PRODUCT_ID = S.PRODUCT_ID
ORDER BY TOTAL_SALES DESC